env:
  browser: true
  commonjs: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 2
    - CallExpression:
        arguments: 'first'

  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
